---
- name: The Great Logic Router
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000

  rules:
    # (i) Case: Value is 'val1'
    - name: Route to specialized playbook
      condition: event.payload.status == "val1"
      action:
        run_playbook:
            name: playbooks/handle_val1_logic1.yml

    # (ii) Case: Value is 'val2'
    - name: Route to External API Call
      condition: event.payload.status == "val2"
      action:
        # Option for transferring http call to playbook and playbook using custom plugin
        run_playbook:
            name: playbooks/mycustom_http.yml

    # (iii) Case: Catch-all
    - name: Default Fallback
      condition: event.payload.status != "val1" and event.payload.status != "val2"
      action:
         run_playbook:
            name: playbooks/default_logger1.yml

