---
- name: The Great Logic Router
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000
  inventory:
    hosts:
      localhost:
        ansible_connection: local

  rules:
    - name: Debug Val1
    condition: event.payload.status == "val1"
    action:
      debug:
        msg: "DEBUG: Condition met for val1
    # (i) Case: Value is 'val1'
    - name: Route to specialized playbook
      condition: event.payload.status == "val1"
      action:
        run_playbook:
            name: playbooks/handle_val1_logic1.yml

    # (ii) Case: Value is 'val2'
    - name: Route to External API Call
      condition: event.payload.status == "val2"
      # Option - use plugin in the rulebook (rather than through playbook)
      action:
        run_module:
            name: ansible.builtin.shell
            module_args:
              cmd: |
                curl -X POST https://api.yourcompany.com/v1/alert \
                  -H "Content-Type: application/json" \
                  -d '{"info": "EDA received val2"}'


    # (iii) Case: Catch-all
    - name: Default Fallback
      condition: event.payload.status != "val1" and event.payload.status != "val2"
      action:
         run_playbook:
            name: playbooks/default_logger1.yml

