---
- name: The Great Logic Router
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000

  rules:
    # (i) Case: Value is 'val1'
    - name: Route to specialized playbook
      condition: event.payload.status == "val1"
      action:
      #  run_playbook:   #This form fails with inventory missing error, unfortunately.
      #      name: playbooks/handle_val1_logic.yml
        run_job_template:
            name: handle_val1
            organization: "Default"
    # (ii) Case: Value is 'val2'
    - name: Route to External API Call
      condition: event.payload.status == "val2"
      action:
        run_job_template:
            name: handle_api_call 
            organization: "Default"
            job_args:
              event_payload: "{{ event.payload }}"
    # (iii) Case: Catch-all
    - name: Default Fallback
      condition: event.payload.status != "val1" and event.payload.status != "val2"
      action:
         #run_playbook:   #This form fails with inventory missing error, unfortunately.
         #   name: playbooks/default_logger.yml
        run_job_template:
            name: handle_default
            organization: "Default"

