---
- name: Simple HelloNew
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.i == 1  # ← Changed from event.i
      action:
        debug:
          msg: "System is working with a Vengeance!!!"

