- name: Handle Val1
  hosts: localhost
  gather_facts: false
  connection: local
  inventory:
    hosts:
      localhost:
        ansible_connection: local
  vars:
    ansible_connection: local
  tasks:
    - name: Trace Step
      debug:
        msg: "I have started. The event that brought me here is: {{ ansible_eda.event }}"
        verbosity: 1

